### ISSUE TITLE
Can I ask you some question?

### ISSUE THREAD

**Issue by loveraven42** [elboletaire/racapp#1]
After I read your code, I don't know where to get the abi of raca. Would you like to tell me that where you get the file of abi  and its executeAction function and its params? Thanks a lot.

**Comment by loveraven42** [comment]
Thanks for you awesome code!

**Comment by loveraven42** [comment]
I try to reverse the font-end of raca website, and it's abi bytecode. But it still can't make sense to me.

**Comment by elboletaire** [comment]
Unfortunately, I could not find the current contracts, so I had to use the ABIs from their website. For that reason, the `AuctionCreated` event do not match with the current contract (apparently they have the ABI definition outdated, or at least it was when I started this app), so you won't be able to listen for that event. Please, if you find the proper event signature, let me know, because I'm also very interested 😅 

BTW, to get the ABI files from their website I had to catch all requests and, with a bit of patience (and beautifying all the codes), find the ABI in their packed code (which tends to be at the end of the files, before a `module.exports`).

Edit: sorry, I was confusing `executeAuction` function with `AuctionCreated` event. I've edited the answer to properly reflect this.

**Comment by loveraven42** [comment]
Ok,let us continue to investigate it.

**Comment by loveraven42** [comment]
hello, I find how to use the function of executeAuction. you can see the details of their things, its json have the value of ```id_in_contract```,  you can execute the function like this ```executeAuction(id_in_contract, price)```

**Comment by loveraven42** [comment]
this is their js ('p__MarketPlace__Detail.983d5a85.async.js')
```js
                var j = Object(w.a)(p.a.mark(function v() {
                    var c;
                    return p.a.wrap(function(d) {
                        for (; ; )
                            switch (d.prev = d.next) {
                            case 0:
                                return Ce(!1),
                                de(!0),
                                ue(!1),
                                d.prev = 3,
                                d.next = 6,
                                _.executeContract(l == null ? void 0 : l.sale_address, ra.abi, "executeAuction", [l == null ? void 0 : l.id_in_contract.toString(), _.parseUnits(((l == null ? void 0 : l.total_price) || 1).toString())]);
```

**Comment by elboletaire** [comment]
I've no problem with that function, you can see how I'm executing `executeAuction` in my code here: https://github.com/elboletaire/racapp/blob/96e6aab4cbec9a28f2c79d5bf14c67cd3224ce2f/src/hooks/wallet.tsx#L68-L108

What I cannot do is read the events like AuctionCreated, because the ABI does not match with their current specification.

**Comment by elboletaire** [comment]
BTW, the only way I've found to get the "id_in_contract" value is by using their API. This is why I'm interested in the AuctionCreated event, but even having that event I doubt I can get the proper `id_in_contract` value; apparently that information is not sent as an output of the event (you can check this by using bscscan).

**Comment by loveraven42** [comment]
ok , if you know how to use ```AuctionCreated ```, you may can use any price to buy their things. :)

**Comment by elboletaire** [comment]
Someone has been able to get it, otherwise there wouldn't be any sniping bots.
